### ISSUE TITLE
TGCN val_dataloader

### ISSUE THREAD

**Issue by gonglucky** [lehaifeng/T-GCN#64]
Hello, may I ask why T-GCN uses test dataset as validation dataset, but function test_step without dataset.

**Comment by martinwhl** [comment]
We choose the model checkpoint with the lowest `Train_Loss`, so you may use the `test_step()` function - there is no difference in our scenario. As there is no validation set, we run test steps in the `validation_step()` function so that the visualizations of metric curves in the TensorBoard are clearer.
